# Generated by Django 4.0.1 on 2022-01-13 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pint',
            name='date_tapped',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
