# Generated by Django 4.0.1 on 2022-01-13 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0001_initial'),
        ('pints', '0002_alter_pint_date_tapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='pint',
            name='bartender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bartender.bartender'),
        ),
    ]
