# Generated by Django 4.0.1 on 2022-01-24 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0001_initial'),
        ('pints', '0003_pint_bartender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pint',
            name='share_url',
            field=models.CharField(default='http://www.google.co.uk/', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pint',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bartender.institution'),
        ),
    ]
