# Generated by Django 4.0.1 on 2022-01-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
